Edit tips
tkt-sankarikoodaajat-2020/sankaristoorit pull request #28
Opened 2020-12-06 15:12 UTC by AlaNeponen

Tehty :

- Toiminnallisuus luotu
- Unit testit fronttiin ja backiin
- E2E testaus

Puuttuu :
- Apidoc

2020-12-06 17:20 UTC, pontushed requested changes
Please check the e2e-tests. Do they conform to the latest merge regarding the intercepts and waits?

2020-12-06 17:20 UTC, pontushed commented on sankaristoorit-ui/cypress/integration/tips_app.spec.js
> +    cy.wait(200)
Cy.wait(200) should not be needed if no other API calls are made between the intercept and wait

2020-12-06 17:27 UTC, AlaNeponen commented
Joo sori olin tehny ton aikasemmin, käyn fiksaa heti ku tästä kerkeen!

su 6. jouluk. 2020 klo 19.20 Pontus Hedlund <notifications@github.com>
kirjoitti:

> *@pontushed* requested changes on this pull request.
>
> Please check the e2e-tests. Do they conform to the latest merge regarding
> the intercepts and waits?
> ------------------------------
>
> In sankaristoorit-ui/cypress/integration/tips_app.spec.js
> <https://github.com/tkt-sankarikoodaajat-2020/sankaristoorit/pull/28#discussion_r537083913>
> :
>
> > @@ -23,6 +23,7 @@ describe('Tips app ', function () {
>      cy.get('#password').type('passWord')
>      cy.get('#login-button').click()
>      cy.wait('@login')
> +    cy.wait(200)
>
> Cy.wait(200) should not be needed if no other API calls are made between
> the intercept and wait
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tkt-sankarikoodaajat-2020/sankaristoorit/pull/28#pullrequestreview-545729450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALDQO6PG35Z6HTIA3VAD6UDSTO4PNANCNFSM4UPMDKBQ>
> .
>

2020-12-07 12:09 UTC, StrappedGlint13 commented on sankaristoorit-backend/routers/ReadingTip.js
> +  }
Hyvältä näyttää ja testit menee läpi mullakin! 

Mietin, että tänne voisi lisätä vähän validointia, kun nyt editointi menee läpi jos title on tyhjä tai url on väärässä formaatissa.

2020-12-07 16:06 UTC, pontushed approved these changes
Hyvähyvä :)

2020-12-07 16:06 UTC, merged